# This workflow runs weekly to clean up releases and tags older than 90 days
name: release-cleanup
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  # Run on schedule
  schedule:
    - cron: '11 12 * * WED'
jobs:
  release-cleanup:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - uses: wow-actions/delete-stale-releases@v1.3.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          delete_tags: true
          keep_latest_days: 90

  cleanup-old-images:
    strategy:
      matrix:
        build: [bookworm, kali, jammy, noble, bennu, docker-hello-world, ntp, vyos]
    name: Delete Untagged Images
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: dataaxiom/ghcr-cleanup-action@v1
        with:
          older-than: 90 day
          packages: sceptre-phenix-images/${{ matrix.build }}.qc2
          keep-n-tagged: 5
          exclude-tags: latest
